stages:
    - build
    - deploy

before_script:
    - export CI_ORIGINAL_REF=$CI_BUILD_REF_NAME
    - "[ \"$CI_BUILD_REF_NAME\" = \"master\" ] && export CI_BUILD_REF_NAME=\"latest\" && export CI_ORIGINAL_REF=\"master\""

build:
    stage: build
    script:
        - docker login -e $DOCKER_LOGIN -p $DOCKER_PASSWORD -u $DOCKER_USERNAME
        - docker build -t ntxcode/unicef-landing-api:$CI_BUILD_REF_NAME .
        - docker push ntxcode/unicef-landing-api:$CI_BUILD_REF_NAME

# test:
#     stage: test
#     script:
#         - docker run -it ntxcode/unicef-landing-api:$CI_BUILD_REF_NAME bundle exec rspec

deploy:
    stage: deploy
    script:
        - "curl -m 300 -X POST -H \"Content-Type: application/json\" -d \"{ \\\"project_name\\\": \\\"unicef\\\", \\\"branch\\\": \\\"${CI_ORIGINAL_REF}\\\" }\" http://dubious-tortoise.staging.ntxdev.com.br:9292/default/hook"
